CREATE TABLE file_contents (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  file_id BIGINT NOT NULL REFERENCES files (id) ON DELETE CASCADE,
  content TEXT NOT NULL,

  UNIQUE (file_id)
);
